mysql:
    image: mysql
    container_name: contadores_mysql
    ports:
        - "3308:3306"
    volumes:
        - ./var/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=qwerty
        - MYSQL_DATABASE=contadores
