mysql:
    image: mysql
    container_name: rhconectium_mysql
    ports:
        - "3311:3306"
    volumes:
        - ./var/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=qwerty
        - MYSQL_DATABASE=rhconect_wprh
